# Generated by Django 4.2.2 on 2023-06-24 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0002_component'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
