# Generated by Django 4.2.2 on 2023-06-24 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0003_rename_user_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Tags',
        ),
    ]
