# Generated by Django 4.2.2 on 2023-06-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0005_tag_delete_tags_rename_tags_component_compid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='compid',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tagid',
        ),
        migrations.AddField(
            model_name='component',
            name='Tags',
            field=models.ManyToManyField(to='component.tag'),
        ),
    ]
