# Generated by Django 4.2.2 on 2023-06-25 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0008_remove_component_tags_component_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='Tags',
        ),
        migrations.AddField(
            model_name='component',
            name='Tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='component.tag'),
        ),
    ]
