# Generated by Django 4.2.2 on 2023-06-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0010_remove_component_tags_component_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='Tags',
            field=models.ManyToManyField(related_name='+', to='component.tag'),
        ),
    ]
