# Generated by Django 4.2.2 on 2023-07-04 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0011_alter_component_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='tag_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='component.tag'),
        ),
    ]
