# Generated by Django 4.2.2 on 2023-07-07 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0012_component_tag_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='tag_id',
        ),
    ]
